### ISSUE TITLE
Incorrect data offset in ri_manifest_sign_v1_5

### ISSUE THREAD

**Issue by cbitsunil** [thesofproject/rimage#52] opened 2021-07-12 05:11 UTC
The data offset that is calculated in ri_manifest_sign_v1_5 function (Pkcs1_5.c) seems to be incorrect.
Currently it is,
 `char *const data1 = (char *)man + MAN_CSS_MAN_SIZE_V1_5;` which offsets into the header.

I think we may have to use,
`char *const data1 = (char *)man + sizeof(struct fw_image_manifest_v1_5);`

Let me know if I'm missing anything here.

**Comment by plbossart** [comment] 2021-07-12 15:59
it's my understanding that the manifest 1.5 is only used on SKL/KBL, which is not supported at the moment. Only 1.8 starting with APL is supported.

@lgirdwood this one is likely for you.

**Comment by lgirdwood** [comment] 2021-07-13 14:26
@cbitsunil thanks for the report, but this is intended as part of the header is signed. v1_5 is used on APL/GLK. Please feel free to submit a PR though that spells this out in a comment (as other may come to the same conclusion).

**Comment by cbitsunil** [comment] 2021-07-15 10:36
@lgirdwood  thanks for the reply.

I'm really not sure if the intention is to include the header for signing (fw_image_manifest_v1_5) here.
If we are including the header then at least the data1 to be pointed to,
`char *const data1 = (char *)man;`

But in the code, the offset added is MAN_CSS_MAN_SIZE_V1_5 which is 174 (The fw_image_manifest_v1_5 size in words).
`char *const data1 = (char *)man + MAN_CSS_MAN_SIZE_V1_5;`

So, here the offset for data1 can be,
1) 0      (if fw_image_manifest_v1_5 header is included for signing)
2) 696  (which is sizeof(struct fw_image_manifest_v1_5) if header is not included for signing)

It is neither 0 nor 696 bytes but 174 bytes which is the fw_image_manifest_v1_5 size in **words**.

Moreover, the size that is passed to pkcs_v1_5_sign_man_v1_5 function is,
`unsigned const size1 = image->image_end - sizeof(*man);`

We are subtracting the size of the header here. So, I think we are not including header for signing.

Please let me know if my understanding is incorrect.

**Comment by lgirdwood** [comment] 2021-07-27 16:38
@cbitsunil apologies, I had to check. This looks like a regression on an unused call path (as v1.5 is only used on very old HW that was deprecated in SOF). This explain why it was not detected by CI. See https://github.com/thesofproject/rimage/pull/57 for fix.

**Comment by marc-hb** [comment] 2021-10-09 05:01
#57 is merged, @cbitsunil can we close this?

**Closed** 2021-10-12 04:53 UTC
